ONSdigital/eq-publisher

.travis.yml

Added travis build configuration to the repository.
For now it just runs the tests. We can add more features such as coverage and linting over time.

Add travis build to Publisher

---

README.md
package.json
src/api/GraphQLApi.js
src/api/GraphQLApi.test.js
src/api/MockGraphQLApi.js
src/api/createGraphQLApi.js
src/main.js

Addressing comments from previously closed PR.

Addresses comments on previously closed PR.

---

README.md
src/eq_schema/Group.js
src/eq_schema/Question.js
src/eq_schema/Questionnaire.js
src/eq_schema/Section.js
src/main.js
src/process/Convert.js
src/validation/SchemaValidator.js

This PR addresses a number of comments on the Publisher code base.
See [trello card](https://trello.com/c/R8EAT3cX/43-questionnaire-publishing-8) for details.
Check that issues have been fixed.
All tests and build should pass.

Fix code issues in eq-publisher

---

package.json
src/api/createGraphQLApi.js
src/main.js

Had to make a few minor changes to allow Publisher to run successfully on CloudFoundry.
All existing tests should pass.
Able to deploy Publisher to CloudFoundry.

Minor tweaks to prepare publisher for CloudFoundry deployment

---

README.md

Fixes #5 README had wrong link URLs

---

.gitignore
package.json
src/eq_schema/Answer.js
src/eq_schema/Answer.test.js
src/eq_schema/Block.js
src/eq_schema/Block.test.js
src/eq_schema/Group.js
src/eq_schema/Group.test.js
src/eq_schema/Question.js
src/eq_schema/Question.test.js
src/eq_schema/Questionnaire.js
src/eq_schema/Questionnaire.test.js
src/eq_schema/Summary.js
src/eq_schema/Summary.test.js
src/main.js
src/process/Convert.js
src/utils/HTMLUtils.js
src/utils/HTMLUtils.test.js
src/validation/ValidationError.test.js
yarn.lock

Adds HTML parsing for titles, descriptions and guidance. Also fixes as a number of bugs that were uncovered during testing of integration with runner
Run tests, review code, test some surveys produced via author in runner.

Rich text integration

---

src/eq_schema/Questionnaire.js
src/eq_schema/Questionnaire.test.js
src/utils/HTMLUtils.js
src/utils/HTMLUtils.test.js

The Publisher was not building the navigation correctly for the final Survey Runner JSON.
This PR adds the logic to build the navigation JSON and adds some tests to ensure correct behaviour.
The schema generated using Publish should contain navigation JSON block containing the section titles.

Add logic for building navigation to Publisher.

---

src/eq_schema/Answer.js
src/eq_schema/Answer.test.js

This PR adds the missing `description` field to the published JSON.
`description` should appear in the output

Fix missing answer description in published schema.

---

package.json
yarn.lock

Forgot to update the schema version in `package.json`. This fixes that
Eyeball it

update to latest schema

---

src/eq_schema/Block.js
src/eq_schema/Block.test.js
src/eq_schema/Group.js
src/eq_schema/Question.js
src/eq_schema/Question.test.js

Fixes issue where question description was being used as section description, and question description is never used.
Follow steps as described in issue, confirm descriptions appear in correct place

use section and question description in correct places. fixes #38

---

data/2_0001.json
data/schema_v1.json
src/eq_schema/Block.js
src/eq_schema/Block.test.js

Changing of Questionnaire to Question now in blocks
In relation to the following PR's: 
- ONSdigital/eq-schema-validator#14
- https://github.com/ONSdigital/eq-survey-runner/pull/1423
Check all instances of Questionnaire have been changed and everything still functions

Eq 1742 rename block types from questionnaire to question

---

package.json
src/api/queries.js
src/eq_schema/Answer.js
src/eq_schema/Answer.test.js
src/main.js
yarn.lock

This PR updates Publisher to deal with recent changes to GraphQL schema.
Child answer Id was removed and replaced with otherAnswer on MultipleChoiceAnswer.
All tests and checks should pass. There should be no errors when run against latest API.

Update publisher to handle other answer

---

src/validation/ValidationApi.js
src/validation/ValidationApi.test.js

There was an error in the validation test, which caused a race condition, meaning the test would occasionally fail.
Tests pass, changes look good

fix validation API test

---

src/middleware/fetchData.js
src/middleware/fetchData.test.js

Improves logging in case of error fetching from graphql API. Will now log the error response from the graphql API, plus the parameters that were sent
Tests pass, code looks good

better logging in case of error fetching from graphql API

---

src/api/queries.js
src/eq_schema/Answer.js
src/eq_schema/Answer.test.js
src/eq_schema/Question.js

Add publisher functionality in order for it to be able to publish multiple choice answers with and "other" answer option.
The tests that check the format should be comprehensive enough to make sure the format is correct and should all pass.

Added other option to publisher

---

.eslintrc
src/api/queries.js
src/eq_schema/Block.js
src/eq_schema/Block.test.js
src/eq_schema/Group.js
src/eq_schema/Group.test.js
src/eq_schema/Questionnaire.js
src/eq_schema/Questionnaire.test.js
src/eq_schema/RoutingConditions.js
src/eq_schema/RoutingDestination.js
src/eq_schema/RoutingRule.js
src/eq_schema/RoutingRule.test.js
src/eq_schema/Section.js
src/eq_schema/Section.test.js
src/eq_schema/block-types/Confirmation.js
src/eq_schema/block-types/Summary.js
src/eq_schema/block-types/Summary.test.js
src/eq_schema/block-types/__snapshots__/Confirmation.test.js.snap
src/utils/mapValues.js
src/validation/ValidationApi.test.js
yarn.lock

Added a function to allow publisher to convert routing rule objects from authors style to runners style.
Tests should pass and the resultant object should match runners validation schema.
https://github.com/ONSdigital/eq-author-api/pull/77

Update publisher for routing

---

src/api/queries.js
src/eq_schema/Block.js
src/eq_schema/RoutingConditions.js
src/eq_schema/RoutingDestination.js
src/eq_schema/RoutingRule.test.js

This PR has been raised in order to revert some the changes made to routing and return it to being able to select multiple options per condition.
Tests pass, changes make sense.

Reverted checkbox implementation

---

package.json
src/api/queries.js
src/eq_schema/Answer.js
src/eq_schema/Answer.test.js
src/eq_schema/Question.js
src/eq_schema/Question.test.js
src/process/Convert.test.js
yarn.lock

This is part of a wider piece of work to introduce answer properties to help the quality of the respondent's input.  
Prior to this work, the concept of answer properties was limited to capturing whether or not an answer is 'mandatory'.  This concept has been refactored to support multiple properties and this PR specifically introduces 'decimal' properties.
[Trello Ticket](https://trello.com/c/f978JRq6/402-properties-decimals-1) 
This PR works in conjunction with the following PR's:
Web App - https://github.com/ONSdigital/eq-author/pull/376
API - https://github.com/ONSdigital/eq-author-api/pull/88
Schema - https://github.com/ONSdigital/eq-author-graphql-schema/pull/46
- Run Tests
- Ensure decimal_places and mandatory are correctly translated to JSON.

Add support for decimal properties in Publisher.

---

src/eq_schema/RoutingConditions.js
src/eq_schema/RoutingRule.test.js

There was a flaw in the logic where if an answer was not set then it could still pass the routing conditions leading to the wrong routes being taken.
Tests pass, schema publishes correctly.
https://github.com/ONSdigital/eq-survey-runner/pull/1663

Added a set condition to all not equals

---

src/eq_schema/block-types/Confirmation.js
src/eq_schema/block-types/__snapshots__/Confirmation.test.js.snap

This PR fixes the broken smoke test by using content question pages for the confirmation page.
This satisfies new rules introduced into the schema validator.
All tests and checks pass.

Change confirmation pages to use Content question type.

---

src/api/queries.js
src/eq_schema/Question.js
src/eq_schema/Question.test.js

Changes to allow publisher to publish a date range as a composite answer.
Tests pass, changes look good and it outputs a valid schema.

Implemented piping based on date ranges

---

src/utils/convertPipes.js

There was an issue when if a Date range was piped then it would have incorrect formatting. This Pr fixes it by passing daterange through the same formatter as all other dates. 
Tests pass, date is correctly formatted.

Added daterange to the list of formattable pipes

---

src/eq_schema/Answer.js
src/eq_schema/Answer.test.js

Translates date format values into appropriate date types.
- Run Tests
- Ensure selecting different date formats translates to the correct date type in the schema
UI: https://github.com/ONSdigital/eq-author/pull/399
API: ONSdigital/eq-author-api#105

Translate date format values to correct date types

---

src/api/queries.js
src/eq_schema/Answer.js
src/eq_schema/Answer.test.js

With the introduction of minimum values in Author, Publisher needed to be updated to support this feature. This PR introduces that functionality.
Changes make sense, correct runner json is outputted and the new test passes.

Implemented validation method in publisher

---

src/eq_schema/Block.js
src/eq_schema/Group.js
src/eq_schema/Group.test.js
src/eq_schema/Questionnaire.js
src/eq_schema/RoutingDestination.js
src/eq_schema/RoutingRule.js
src/eq_schema/RoutingRule.test.js
src/eq_schema/Section.test.js

Implements an accepted work-around to introduce the concept of routing between sections based on checkbox answers.
Tests pass and when passed a questionnaire with routing between sections publisher should output working Runner schema which allows for this functionality.

Implement routing to a new section

---

src/api/queries.js
src/eq_schema/Answer.js
src/eq_schema/Answer.test.js

Add the ability to publish earliest date validation to survey runner.
1. Run the tests and prove they work
2. Create a questionnaire with an earliest date validation, then preview it and ensure that it works in survey runner.

449 - Earliest date validation

---

README.md

Added documentation for new environment variable
Removed documentation for Graphql endpoint
Read Readme to make sure it looks ok

Updated env variables in docs

---

package.json
yarn.lock

Upgrade to husky 1.0.1
Make sure tests pass

Upgrade to husky 1.0.1

---

package.json
yarn.lock

Closes #88
Upgrade graphql to 14.0.2
Run all tests and make sure that it system runs correctly

fix(package): update graphql to version 14.0.2

---

src/api/queries.js
src/eq_schema/Block.js
src/eq_schema/Question.js
src/eq_schema/Question.test.js
src/eq_schema/Questionnaire.js
src/eq_schema/Questionnaire.test.js
src/process/Convert.test.js
src/utils/convertPipes.js
src/utils/convertPipes.test.js

Publish user defined metadata
1. Ensure tests pass.
2. Ensure you can publish a questionnaire without metadata.
3. Ensure that you cannot publish a questionnaire with metadata that isn't used.

492 - Publish metadata

---

.eslintrc
package.json
yarn.lock

- Upgrades to latest [eslint](https://www.npmjs.com/package/eslint) and  [eslint-config-eq-author](https://www.npmjs.com/package/eslint-config-eq-author)
- Ensure tests pass
- Ensure [new linting rules](https://github.com/ONSdigital/eslint-config-eq-author/pull/7) work as expected

Upgrade eslint and eslint config

---

src/eq_schema/Answer.js
src/eq_schema/Answer.test.js

This PR adds the method to allow us to validate based on a current date, and also adds the tests required.
New tests pass and a valid schema with the correct validations is created.

Implemented validation on start date

---

src/api/queries.js
src/eq_schema/Block.js
src/eq_schema/Group.js
src/eq_schema/Group.test.js
src/eq_schema/Section.js

This Pr modifies the build groups structure to allow publisher to publish surveys with a section introduction.
Tests pass and when tested against a survey which includes a introduction the schema is correct and displays the introduction as it should.

Add the ablitiy to create section introductions

---

src/api/queries.js
src/eq_schema/Block.js
src/eq_schema/Block.test.js
src/eq_schema/Group.js
src/eq_schema/Group.test.js
src/eq_schema/RoutingDestination.js
src/eq_schema/builders/confirmationPage/ConfirmationPage.js

This PR allows publisher to publish confirmation pages while also keeping the routing rules for them consistent.
E2E checks pass, new tests pass and the code looks good.

Allow publish of confirmation pages
