data/schema_v1.json, package.json, src/api/queries.js, src/eq_schema/Questionnaire.js, src/eq_schema/Questionnaire.test.js, src/main.js, yarn.lock
This PR adds two additional properties in the resulting JSON produced by Publisher.
These properties, `form_type` and `eq_id` are required in order for the [go-launch-a-survey](https://github.com/ONSdigital/go-launch-a-survey) service to generate valid claims when launching with a URL.
For now, these values can be anything. Currently setting them to be the same as the questionnaire id. This might change over time.
Observe that `form_type` and `eq_id` are present in the resulting JSON.
All tests and checks should pass.
=> Add missing properties form_type and eq_id required for go-launch-a-survey.

src/eq_schema/Question.js, src/eq_schema/Question.test.js
Add support for date range answer types.
Author will allow users to mix DateRange answer types with other answers (this is not supported by runner and causes errors). We will eventually restrict this in the UI. In the meanwhile, I have added logic here to drop all non-DateRange answers from a page when a DateRange is found.
Review code, run tests, test previewing with author
=> add support for DateRange answers

src/eq_schema/Questionnaire.js, src/eq_schema/Questionnaire.test.js
Previously the publisher used data version 0.0.1 which failed upon submission when previewing since it requires q_codes (which Author does not supply).
Changing the data version to 0.0.2 should allow the submission to work. Since 0.0.2 does not require q_codes.
Observed that published schema has a data version of 0.0.2. 
And submission should work when previewing.
=> Enable submission during preview.

.codecov.yml, package.json, src/main.js, src/middleware/errorHandler.js, src/middleware/errorHandler.test.js, src/middleware/fetchData.js, src/middleware/fetchData.test.js, src/middleware/respondWithData.js, src/middleware/respondWithData.test.js, src/middleware/schemaConverter.js, src/middleware/schemaConverter.test.js, src/process/Convert.js, src/process/Convert.test.js, src/validation/ValidationError.js, src/validation/createSchemaValidator.js, yarn.lock
Adds structured (JSON) logging to the Publisher.
Removes the basic HTTP logging (morgan) and replaces it with `express-pino-logger`.
Logs errors before returning the response.
Observe that Publisher produces JSON structured HTTP logs.
Observe that errors are logged if there's a problem during publishing/conversion.
=> Add structured logging to Publisher.

.codecov.yml
eq-publisher is currently failing on master due to codecov coverage failure.
This failure is result of the coverage being fixed by a prior commit. Previously it was erroneously reporting 100% coverage.
This PR sets the coverage target to 85% as a baseline.
Codecov check should pass.
=> Set codecov target coverage to 85%

package.json, src/eq_schema/Answer.js, src/eq_schema/Answer.test.js, src/eq_schema/Block.js, src/eq_schema/Block.test.js, src/eq_schema/Question.js, src/eq_schema/Question.test.js, src/utils/convertPipes.js, src/utils/convertPipes.test.js, yarn.lock
Adds support for piped values coming from author
* Author uses a different format to runner so that we have more flexibility/room for change in future
* Adds functions for processing HTML to convert from author format to runner format
* Integrates conversion step into Question title and guidance and Block description
Run tests. Review code. You can test conversion by either manually entering piped value into your DB (format is `<span data-pipe="answers" data-id="[an answer id]" data-type="[the answer type]">[Answer test]</span>`), or testing with the [WIP author branch](https://github.com/ONSdigital/eq-author/tree/draft-piping)
=> Support piping

data/schema_v1.json, src/eq_schema/Answer.js, src/eq_schema/Answer.test.js
Fixes [#257](https://github.com/ONSdigital/eq-author/issues/257).
Prior to this PR, optional description text entered for an Option in either Checkbox or Radio answer types were not included in the Published schema (and not visible in Runner preview).
This PR fixes this and includes the description text in the published output JSON.
The description text should appear for Checkbox/Radio options when previewing the questionnaire.
=> Fixes missing description text under checkbox/radio options.

src/utils/convertPipes.js, src/utils/convertPipes.test.js
Process to find/convert piped values should handle null/undefined
Follow steps described in #33 before and after change
=> fix issue with null values for pipeable fields. fixes #33

src/eq_schema/Answer.js, src/eq_schema/Answer.test.js
Fixes #35.
Should now handle null values in the `option.description` field.
Error should no longer be observed. Description will only appear in the outputted JSON if value provided.
=> Fixes #35. Error when null answer option description.

src/main.js
Fixes https://github.com/ONSdigital/eq-compose/issues/6.
The publisher application was not binding to address 0.0.0.0 when running
using docker compose, since the HOSTNAME environment variable was being
set by the docker engine and resolving to the container name.
This resulted in connection refused errors being reported by publisher
when the survey launcher attempted to request the survey JSON.
This fix, changes publisher to always bind to 0.0.0.0.
Should be able to preview questionnaires when running eq-compose.
=> Fixes broken preview when running with eq-compose.

.travis.yml, Dockerfile
Changed travis config so that Publisher is built in node LTS container (should be Node 8).
Changed Dockerfile configuration so that publisher runs in Node 8 environment.
All tests and checks should pass. Build should succeed.
Visual inspection of travis build log to confirm Node 8 runtime is being used.
Pull down the branch docker image/ docker inspect to ensure that node 8 is used.
Run the newly built docker image, should work as expected.
=> Switch publisher to build and run on node 8.

package.json, yarn.lock
This PR is an attempt to fix the broken deployment to AWS ECS. The deployment is failing due to missing `request` library when deploying Publisher.
This PR adds `request` as a dependency of `eq-publisher` so that it gets installed as part of building the docker image.
Publisher should be deployed successfully.
=> Fix broken concourse build due to missing request library.

README.md, docker-compose.yml, package.json
Since switching to docker-compose, debugging was not possible. This change starts the app with the `--inspect` flag, and opens the debug port so that debuggers can be attached
Ensure everything looks good. Use this debugger config for vscode to test it out:
```json
{
"version": "0.2.0",
"configurations": [
{
"name": "Attach to Container",
"type": "node",
"request": "attach",
"port": 5858,
"address": "localhost",
"restart": true,
"sourceMaps": false,
"localRoot": "${workspaceRoot}",
"remoteRoot": "/app",
"protocol": "inspector"
}
]
}
```
=> Enable attaching a debugger

src/eq_schema/Answer.js, src/eq_schema/Group.js, src/eq_schema/Group.test.js, src/eq_schema/Questionnaire.js, src/eq_schema/Questionnaire.test.js, src/eq_schema/Section.js, src/eq_schema/Section.test.js
Groups are now children of sections in the runner schema. This change is for publisher to correctly transform authored schemas into the updated runner schema.
See https://github.com/ONSdigital/eq-survey-runner/pull/1473
Check that authored questionnaires can still be previewed
=> Promote section in schema

README.md, docker-compose.yml
We used port `5858` in both eq-author-api and eq-publisher, meaning they would clash if you start both apps. This switches debug port for publisher to `5859`, and updates README to document this.
=> don't use same debug port as eq-author-api

src/process/Convert.js, src/validation/ValidationError.js, src/validation/ValidationError.test.js, src/validation/__snapshots__/ValidationError.test.js.snap
We weren't giving much information in the event of an error from the schema validator. This PR makes a change so that the JSON supplied to schema-validator is given in publisher's HTTP response. 
Check error message is reasonable, code looks good
=> improve reporting of schema validation errors

src/validation/ValidationApi.js, src/validation/ValidationApi.test.js
Schema validator will start sending `400` status code for invalid schemas. The request library we rejects the promise that scenario. Our existing code did not handle that possibility. This PR updates publisher to handle this, whilst maintaining backwards compatibility. Publisher should be merged/deployed before this PR: https://github.com/ONSdigital/eq-schema-validator/pull/42
Code looks OK, tests pass
=> Handle 400 response from validator

src/validation/ValidationApi.js, src/validation/ValidationApi.test.js
Removes backwards compatibility with older schema-validator (where `200` status was returned even in case of validation failure).
It felt clearer to use promises directly, rather than async/await, so I switched to that. 
Code looks good, tests pass
=> remove backwards compatibility with older schema-validator

src/api/queries.js, src/eq_schema/Question.js, src/eq_schema/Question.test.js
Implemented changes to remove the hard-coded label and secondary label on date-ranges and allowed publisher to publish user defined labels.
All tests should pass and in the resultant json schema the date range should show user-defined labels
- ~ONSdigital/eq-author-graphql-schema#28~
=> Added second label type for date ranges

src/eq_schema/Answer.js, src/eq_schema/Answer.test.js
Answer alias is removed from runner in https://github.com/ONSdigital/eq-survey-runner/pull/1533
This removes it from publisher.
Do not merge until runner PR is merged.
=> Remove answer alias from publisher

src/eq_schema/Answer.js, src/eq_schema/Answer.test.js, src/eq_schema/Block.js, src/eq_schema/Block.test.js, src/eq_schema/Group.js, src/eq_schema/Group.test.js, src/eq_schema/Question.js, src/eq_schema/Question.test.js, src/eq_schema/Questionnaire.test.js, src/eq_schema/Section.js, src/eq_schema/Section.test.js, src/middleware/fetchData.test.js, src/utils/convertPipes.js, src/utils/convertPipes.test.js
Since runner has dropped support for aliases, we need to use IDs for piping. Currently IDs contain hyphens, which mean they are not valid python identifiers. This PR drops the hyphen. 
* Previous format: `[type]-[id]`
* New format: `[type][id]`
This PR also fixes some issues i discovered with `fetchData` tests
Create questionnaire with piping in author, preview in runner, ensure values are piped correctly
=> Fix piping

src/eq_schema/Questionnaire.js, src/eq_schema/Questionnaire.test.js
This PR adds mandatory schema-level metadata into the resulting JSON in order to support a change being made to the eQ schema validator.
For now, the values have been hard coded. There is another story on the backlog for to modify Author to allow users to dynamically specify metadata values. Publisher will need to be updated again in a future change to support this.
Changes look okay, tests and checks pass.
Should generate valid JSON against schema validator branch `specify-required-metadata-in-schema`.
- https://github.com/ONSdigital/eq-schema-validator/pull/50
=> Add mandatory metadata to published runner schema.

src/eq_schema/Questionnaire.js, src/eq_schema/Questionnaire.test.js
The introduction page expects RU Name to be present for default and northernireland themes.
This PR adds ru_name as required metadata in the schemas.
=> RU Name mandatory in metadata

src/eq_schema/Block.js, src/eq_schema/Block.test.js, src/eq_schema/RoutingRule.test.js, yarn.lock
The implementation of basic routing on Author allows authors to specify rules that goto future pages in the same section, future sections and the end of the questionnaire.
Survey runner does not currently support routing between sections of the questionnaire. As such, the ability to navigate to future sections has been temporarily removed from routing.
A consequence of this is that a further change is being made to prevent authors from specifying routing rules on the last page of a section.
This PR makes a specific check within author to prevent routing rules from being processed for the last page in a section. This is to work around an edge case where a page may become the last page in a section e.g. after deletion of another page.
Hopefully once the ability to route across sections has …
=> Prevent routing on last page in section

src/api/queries.js, src/eq_schema/RoutingConditions.js, src/eq_schema/RoutingRule.test.js
Routing was broken on "other" options as these options are in a different path on the answer object. This PR fixes this issue and allows routing based on other options.
The new test passes and routing on "other" options is possible again.
=> Fixed the issue preventing routing from working with 'other' options.

.eslintrc, package.json, yarn.lock
Closes #68
GreenKeeper automatically created a PR #68 to update eslint to 5.0.0. This wasn't merged before a latter version was released and so this supersedes that.
Check later version behaves as expected.
=> chore(package): update eslint to version 5.0.1

src/eq_schema/Answer.js, src/eq_schema/Answer.test.js
This PR is a hotfix for an error being observed in preprod when previewing the census questionnaire.
A check has been added to prevent destructuring minValue validation if validation is undefined or null. A failing test has also been added.
Changes look sensible and all checks and tests pass.
=> Fix error when destructuring min value when validation is undefined.

src/api/queries.js, src/eq_schema/Answer.js, src/eq_schema/Answer.test.js
This PR add the methods allowing Publisher to convert Author mutually exclusive answers to Runner acceptable format. 
Tests are passing and the new schema pass validation and is displayed correctly within Runner.
https://github.com/ONSdigital/eq-author-api/pull/109
=> Added methods to allow mutually exclusive

src/eq_schema/Block.js, src/eq_schema/Block.test.js, src/eq_schema/Group.js, src/eq_schema/RoutingRule.test.js
Removed block titles. Groups no longer pass title variables down to blocks. Tests updated to reflect this.
Review code and preview survey to make sure titles do not show up for blocks but section titles still show in right hand navigation.
=> Remove block title from published schema

src/eq_schema/Question.js, src/eq_schema/Question.test.js, src/utils/HTMLUtils.js, src/utils/convertPipes.js, src/utils/convertPipes.test.js
There is an issue piping currency answers. It turns out that survey runner no longer support the `format_currency` Jinja filter. Instead, the recommended approach is to use the `format_currency(value, unit)` context function.
This PR makes changes to Publisher so that it uses the new approach to formatting currency answers.
It also changes more generally how piped values are represented in the resulting schema.
Prior to this change answers and metadata were piped like this:
`{{answers.answer123}}` and `{{metadata.ru_ref}}`.
This PR changes the format to look like this:
`{{ answers['answer123'] }}` and `{{ metadata['ru_ref'] }}` as per recommendations made by the runner team.
To fully realise this change, I also had to ensure that the single quotes in piped values are not escaped in the …
=> Fix issue unable to pipe currency answers.

src/api/queries.js, src/eq_schema/Answer.js, src/eq_schema/Answer.test.js
Implement the changes to publish max value validation against previous answers.
1. Ensure tests pass.
1. Ensure that you can publish a schema with two number answers where the second answer is reliant on the first. Then check that answer given in the first is used to validate the second.
=> 651 - Max value validation against previous answers

src/eq_schema/Answer.js, src/eq_schema/Answer.test.js
This change is a temporary workaround to fix the broken preview for questionnaires containing mutually exclusive checkbox options.
Previewing questionnaires that contain mutually exclusive checkbox answers broke as a result of a recent change to schema validator. The schema for mutually exclusive answers has changed and is now incompatible with publisher.
This PR is a temporary fix until a further change can be made to publisher to adhere to the new schema.
Following this change it should be possible to preview questionnaires containing mutually exclusive options once again, but the mutually exclusive checkbox option will appear in line with all of the other options and will not stand alone in its own OR option.
- Checkout master
- Create a questionnaire containing a Checkbox answer with …
=> Temporary fix for broken preview with mutually exclusive.

src/api/queries.js, src/eq_schema/Answer.js, src/eq_schema/Answer.test.js
- Adds the previous answer for earliest and latest date validation
- Run tests
=> Add previous answer to earliest and latest date validation

src/api/queries.js, src/eq_schema/Answer.js, src/eq_schema/Answer.test.js
- Adds the metadata for earliest and latest date validation
- Run tests
=> Add metadata to earliest and latest date validation

src/api/queries.js
There's a reference to section description in the query that gets executed by publisher that needs to be removed before https://github.com/ONSdigital/eq-author-api/pull/145 gets merged.
Change looks okay. All tests and checks should pass.
=> Remove deprecated field reference from publisher.

src/eq_schema/builders/routingcondition/NumberRoutingCondition.js
Due to Runner limitations we were not able to include the inclusive comparators on the first pass of routing based on a number. This has since been resolved so this PR adds that functionality. 
Tests pass and you are able to publish a survey with an inclusive comparator in the routing conditions.
=> Added inclusive number options to routing

src/middleware/respondWithData.js, src/middleware/respondWithData.test.js
When an author adds whitespace at the end of values accidentally. This is passed to runner and displayed to respondents.
This PR trims whitespace from all values within the generated schema.
Add whitespace at the beginning and end of some text in author. 
Publish the schema and observe that the whitespace has been removed.
=> Trim whitespace in schema values
